### ISSUE TITLE
語法錯誤

### ISSUE THREAD

**Issue by GlaciusTW** [bruce68tw/bao_app#1]
呼叫 HttpUt.getJsonAsync 時，第四個參數需要是Map的型態，但真正傳進去的卻是 DtDto，這有語法錯誤。

**Comment by bruce68tw** [comment]
使用 HttpUt.getJsonAsync 時, 第三個參數 bool jsonArg 表示後端參數種類, jsonArg = true, 則後端為 Model, 例如 DtDto, jsonArg = false, 則後端為一般型態資料, 例如 int, string。

**Comment by GlaciusTW** [comment]
Got it, thanks.
